apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  labels:
    app: clickhouse
spec:
  clusterIP: None
  ports:
    - port: 8123
      targetPort: 8123
      name: http
    - port: 9000
      targetPort: 9000
      name: native
  selector:
    app: clickhouse
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clickhouse
  labels:
    app: clickhouse
spec:
  serviceName: "clickhouse"
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
        - name: clickhouse
          image: clickhouse/clickhouse-server:latest
          ports:
            - containerPort: 8123
              name: http
            - containerPort: 9000
              name: native
          readinessProbe:
            tcpSocket:
              port: native
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 12
          envFrom:
            - secretRef:
                name: clickhouse-secret
          env:
            - name: TZ
              value: "Asia/Hong_Kong"
            - name: CLICKHOUSE_DB
              value: "langfuse"
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              memory: "2Gi"
          volumeMounts:
            - name: clickhouse-data
              mountPath: /var/lib/clickhouse
            - name: clickhouse-config
              mountPath: /etc/clickhouse-server/config.d/memory-limits.xml
              subPath: memory-limits.xml
      volumes:
        - name: clickhouse-data
          hostPath:
            path: /mnt/workspaces/clickhouse/data
            type: DirectoryOrCreate
        - name: clickhouse-config
          configMap:
            name: clickhouse-configmap
